Repository afritzler/takumai, pull requests merged in 2024-10, with the labels that each got.

#1 Add usage to readme
  README.md
Labels: documentation, chore, size/XS

#2 Add release branch creator workflow
  .github/workflows/release-branch.yml
Labels: enhancement, size/M

#3 Fix permissions in branch creation workflow
  .github/workflows/release-branch.yml
Labels: bug, size/XS

#4 Generate release notes for release branches
  .github/workflows/release-branch.yml
  .github/workflows/release-drafter.yml
Labels: enhancement, size/XS

#5 Only run release drafter on release branches
  .github/workflows/release-drafter.yml
Labels: enhancement, size/XS

#8 Fix cherry pick workflow
  .github/workflows/cherry-pick.yml
Labels: bug, size/S

#9 Fix git cherry pick usage
  .github/workflows/cherry-pick.yml
Labels: bug, size/XS

#10 Fix cherry pick sha calculation
  .github/workflows/cherry-pick.yml
  .github/workflows/release-drafter.yml
Labels: bug, size/M

#12 Fix github author
  .github/workflows/cherry-pick.yml
Labels: bug, size/XS

#13 Switch cherry pick action
  .github/workflows/cherry-pick.yml
  .github/workflows/release-drafter.yml
Labels: enhancement, size/L

#17 [Backport release-v0.3] New backport workflow
  .github/workflows/cherry-pick.yml
Labels: size/L

#18 Update docs
  README.md
Labels: documentation, enhancement, size/XS, backport release-v0.3

#19 [Backport release-v0.3] Update docs
  README.md
Labels: documentation, size/XS

#20 Update awesome docs
  README.md
Labels: documentation, enhancement, size/XS

#21 [Backport release-v0.3] Update awesome docs
  README.md
Labels: documentation, size/XS

#23 Update docs
  README.md
Labels: documentation, enhancement, size/XS, minor

#24 [Backport release-v0.4] Update docs
  README.md
Labels: documentation, size/XS

#25 Update docs
  README.md
Labels: documentation, enhancement, size/XS, minor

#26 [Backport release-v0.4] Update docs
  README.md
Labels: documentation, size/XS

#27 Awesome docs update
  README.md
Labels: documentation, enhancement, size/XS

#28 [Backport release-v0.6] Awesome docs update
  README.md
Labels: documentation, size/XS

#30 Added awesome docs
  README.md
Labels: minor

#31 Foo docs added
  README.md
Labels: documentation, enhancement, size/XS

#32 [Backport release-v0.7] Foo docs added
  README.md
Labels: documentation, size/XS

#37 Update README.md
  README.md
Labels: documentation, enhancement
